name: Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-vscode-extension:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: 'extensions/vscode/package-lock.json'

      - name: Install VSCE
        run: npm install -g @vscode/vsce

      - name: Install dependencies
        run: yarn install --network-timeout 1000000

      - name: Build VSCode extension
        run: |
          yarn vscode:install
          yarn vscode:compile
          cd extensions/vscode && vsce package --out keykeeper-vscode-${{ github.ref_name }}.vsix

      - name: Upload VSCode extension artifact
        uses: actions/upload-artifact@v4
        with:
          name: vscode-extension
          path: extensions/vscode/keykeeper-vscode-${{ github.ref_name }}.vsix

  release:
    needs: build-vscode-extension
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-22.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libwebkit2gtk-4.0-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            patchelf \
            libssl-dev \
            pkg-config

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Sync node version and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'yarn'

      - name: Install frontend dependencies
        run: yarn install --network-timeout 1000000

      - name: Build frontend
        run: yarn build

      - name: Download VSCode extension
        if: matrix.platform == 'ubuntu-22.04'
        uses: actions/download-artifact@v4
        with:
          name: vscode-extension
          path: ./vscode-extension

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__
          releaseName: 'KeyKeeper v__VERSION__'
          releaseBody: 'See the assets to download and install this version.'
          releaseDraft: true
          prerelease: false
          includeUpdaterJson: true
          args: ${{ matrix.platform == 'macos-latest' && '--target universal-apple-darwin' || '' }}

      - name: Upload VSCode extension to release
        if: matrix.platform == 'ubuntu-22.04'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: ./vscode-extension/keykeeper-vscode-${{ github.ref_name }}.vsix
          draft: true